version: '3'

services:
  db:
    build: ./db
    ports:
        - 1433:1433
  ai:
    build: ./ai
    ports: 
        - 5390:5390
  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - db
